const data = [
  {
    id: 4,
    name: "Level 3",
    abbr: "L-3",
    courseId: 1,
    type: "course",
    Meta: [
      {
        id: 5,
        courseLogo:
          "https://del1.vultrobjects.com/crmaswinibajaj/CRM/Platform/C3.png",
        longDescription: null,
        shortDescription:
          "Designed for graduates or Level 2 qualifiers, this 180-hour program prepares you for essay questions and integrates cross-subject concepts through focused mentoring.",
        courseId: 4,
        price: "19001",
        purchasable: true,
        hours: 180,
      },
    ],
    includeParent: null,
    Options: [],
    ExtraOptions: [],
    Course: {
      id: 1,
      name: "Chartered Financial Analyst",
      abbr: "CFA",
      courseId: null,
      order: null,
      type: "course",
      expiry: null,
      includeParent: null,
      isActive: null,
      Meta: [],
      Course: null,
    },
    Courses: [
      {
        id: 14,
        name: "Portfolio Management",
        abbr: "P",
        courseId: 4,
        type: "pathway",
        Meta: [],
        Options: [],
        ExtraOptions: [],
        Courses: [
          {
            id: 17,
            name: "2025",
            abbr: "2025",
            courseId: 14,
            type: "session",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 23,
                name: "Aug",
                abbr: "Aug",
                courseId: 17,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
          {
            id: 94,
            name: "2026",
            abbr: "2026",
            courseId: 14,
            type: "session",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 95,
                name: "Feb",
                abbr: "Feb",
                courseId: 94,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
        ],
      },
      {
        id: 15,
        name: "Private Markets",
        abbr: "M",
        courseId: 4,
        type: "pathway",
        Meta: [],
        Options: [],
        ExtraOptions: [],
        Courses: [
          {
            id: 18,
            name: "2025",
            abbr: "2025",
            courseId: 15,
            type: "session",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 24,
                name: "Aug",
                abbr: "Aug",
                courseId: 18,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
          {
            id: 96,
            name: "2026",
            abbr: "2026",
            courseId: 15,
            type: "session",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 98,
                name: "Feb",
                abbr: "Feb",
                courseId: 96,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
        ],
      },
      {
        id: 16,
        name: "Private Wealth",
        abbr: "W",
        courseId: 4,
        type: "pathway",
        Meta: [],
        Options: [],
        ExtraOptions: [],
        Courses: [
          {
            id: 19,
            name: "2025",
            abbr: "2025",
            courseId: 16,
            type: "session",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 25,
                name: "Aug",
                abbr: "Aug",
                courseId: 19,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
          {
            id: 97,
            name: "2026",
            abbr: "2026",
            courseId: 16,
            type: "session",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 99,
                name: "Feb",
                abbr: "Feb",
                courseId: 97,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
        ],
      },
      {
        id: 56,
        name: "Pathways",
        abbr: "Pathways",
        courseId: 4,
        type: "course",
        Meta: [
          {
            id: 6,
            courseLogo: null,
            longDescription: null,
            shortDescription:
              "Specialize in Wealth Management, Private Markets, or Public Markets with expert-led modules on financial planning, private equity, and advanced investment strategies.",
            courseId: 56,
            price: "5500",
            purchasable: true,
            hours: null,
          },
        ],
        Options: [],
        ExtraOptions: [],
        Courses: [
          {
            id: 26,
            name: "Portfolio Management",
            abbr: "PP",
            courseId: 56,
            type: "pathway",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 29,
                name: "2025",
                abbr: "2025",
                courseId: 26,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
          {
            id: 27,
            name: "Private Markets",
            abbr: "MP",
            courseId: 56,
            type: "pathway",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 30,
                name: "2025",
                abbr: "2025",
                courseId: 27,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
          {
            id: 28,
            name: "Private Wealth",
            abbr: "WP",
            courseId: 56,
            type: "pathway",
            Meta: [],
            Options: [],
            ExtraOptions: [],
            Courses: [
              {
                id: 31,
                name: "2025",
                abbr: "2025",
                courseId: 28,
                type: "session",
                Options: [],
                ExtraOptions: [],
                Meta: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
