export const dtQuestions = [
  {
    id: 11,
    questionText: "multiple image ",
    attachments: [
      {
        link: "http://192.168.1.99:9000/crm/CRMTest/doubtforum/Question_31693b7f-64f7-4bdc-b323-6d4636c463f6_11.jpg",
        type: "image",
      },
      {
        link: "http://192.168.1.99:9000/crm/CRMTest/doubtforum/Question_d552ac54-e8e9-4803-a345-30395078190f_11.jpg",
        type: "image",
      },
      {
        link: "http://192.168.1.99:9000/crm/CRMTest/doubtforum/Question_00da6d10-ac4b-4c0f-a6d7-30d1376efa58_11.jpg",
        type: "image",
      },
    ],
    fallNumber: 4,
    userId: 235,
    sourceId: 1,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-06T10:22:57.713Z",
    updatedAt: "2025-03-06T10:22:58.540Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 1,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 4,
      Subject: [
        {
          Subject: {
            id: 669,
            name: "D. demonstrate the use of a time line in modeling and solving time value of money problems",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 10,
    questionText: "question with source id ",
    attachments: [],
    fallNumber: 1,
    userId: 235,
    sourceId: 2,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-06T09:50:15.839Z",
    updatedAt: "2025-03-06T09:50:15.848Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 0,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 1,
      Subject: [
        {
          Subject: {
            id: 666,
            name: "A. interpret interest rates as required rates of return, discount rates, or opportunity costs",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 9,
    questionText: "Question With source",
    attachments: [],
    fallNumber: 3,
    userId: 235,
    sourceId: 4,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-06T08:15:43.299Z",
    updatedAt: "2025-03-06T08:15:43.304Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 0,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 3,
      Subject: [
        {
          Subject: {
            id: 668,
            name: "C. calculate and interpret the future value (FV) and present value (PV) of a single sum of money, an ordinary annuity, an annuity due, a perpetuity (PV only), and a series of unequal cash flows",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 8,
    questionText: "Question With source",
    attachments: [],
    fallNumber: 3,
    userId: 235,
    sourceId: 4,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-06T08:14:09.544Z",
    updatedAt: "2025-03-06T08:14:09.549Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 0,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 3,
      Subject: [
        {
          Subject: {
            id: 668,
            name: "C. calculate and interpret the future value (FV) and present value (PV) of a single sum of money, an ordinary annuity, an annuity due, a perpetuity (PV only), and a series of unequal cash flows",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 7,
    questionText: "required questions ⁉️",
    attachments: [],
    fallNumber: 528,
    userId: 235,
    sourceId: null,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-05T09:51:08.731Z",
    updatedAt: "2025-03-05T09:51:08.738Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 1,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 528,
      Subject: [
        {
          Subject: {
            id: 1326,
            name: "A. ",
            order: null,
            type: "los",
            Subject: {
              id: 1325,
              name: "5. Discounted Cash Flow",
              order: null,
              type: "chapter",
              Subject: {
                id: 1318,
                name: "BasicConcepts",
                order: 0,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
        {
          Subject: {
            id: 1338,
            name: "A. ",
            order: null,
            type: "los",
            Subject: {
              id: 1337,
              name: "5. Forwards and Futures",
              order: null,
              type: "chapter",
              Subject: {
                id: 1318,
                name: "BasicConcepts",
                order: 0,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 6,
    questionText: "testing 💫",
    attachments: [],
    fallNumber: 2,
    userId: 235,
    sourceId: null,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-05T09:38:21.780Z",
    updatedAt: "2025-03-05T09:38:21.784Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 0,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 2,
      Subject: [
        {
          Subject: {
            id: 667,
            name: "B. explain an interest rate as the sum of a real risk-free rate and premiums that compensate investors for bearing distinct types of risk",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 5,
    questionText: "Add new",
    attachments: [],
    fallNumber: 3,
    userId: 235,
    sourceId: null,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-05T06:18:24.237Z",
    updatedAt: "2025-03-05T06:18:24.720Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 1,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 3,
      Subject: [
        {
          Subject: {
            id: 668,
            name: "C. calculate and interpret the future value (FV) and present value (PV) of a single sum of money, an ordinary annuity, an annuity due, a perpetuity (PV only), and a series of unequal cash flows",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 4,
    questionText: "Question",
    attachments: [],
    fallNumber: 3,
    userId: 235,
    sourceId: null,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-04T10:45:46.581Z",
    updatedAt: "2025-03-04T10:45:46.588Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 0,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 3,
      Subject: [
        {
          Subject: {
            id: 668,
            name: "C. calculate and interpret the future value (FV) and present value (PV) of a single sum of money, an ordinary annuity, an annuity due, a perpetuity (PV only), and a series of unequal cash flows",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 3,
    questionText: "Question",
    attachments: [],
    fallNumber: 3,
    userId: 235,
    sourceId: null,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-04T10:14:46.048Z",
    updatedAt: "2025-03-04T10:14:46.070Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 0,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 3,
      Subject: [
        {
          Subject: {
            id: 668,
            name: "C. calculate and interpret the future value (FV) and present value (PV) of a single sum of money, an ordinary annuity, an annuity due, a perpetuity (PV only), and a series of unequal cash flows",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
  {
    id: 2,
    questionText: "Question",
    attachments: [
      {
        link: "http://192.168.1.99:9000/crm/CRMTest/doubtforum/Question_cb2d73cd-b195-4371-a8d1-046a4ec30d0e_2.png",
        type: "image",
      },
    ],
    fallNumber: 3,
    userId: 235,
    sourceId: null,
    employeeId: null,
    likeCount: null,
    dislikeCount: null,
    createdAt: "2025-03-03T08:17:42.699Z",
    updatedAt: "2025-03-03T08:17:42.890Z",
    User: {
      id: 235,
      fname: "Durgesh",
      lname: "Tiwari",
      profile: null,
    },
    _count: {
      Answer: 0,
      Views: 1,
    },
    Likes: [],
    Pinned: [],
    Views: [],
    FallNumber: {
      id: 3,
      Subject: [
        {
          Subject: {
            id: 668,
            name: "C. calculate and interpret the future value (FV) and present value (PV) of a single sum of money, an ordinary annuity, an annuity due, a perpetuity (PV only), and a series of unequal cash flows",
            order: null,
            type: "los",
            Subject: {
              id: 665,
              name: "PR1. Interest Rates, Present Value, and Future Value",
              order: null,
              type: "chapter",
              Subject: {
                id: 664,
                name: "Quantitative Methods-Pre-requisites",
                order: 1,
                type: "subject",
                Subject: null,
              },
            },
          },
        },
      ],
    },
  },
];
